import mongoose from 'mongoose';

import {
  FIELD_INCIDENT_TYPES,
  FIELD_INCIDENT_RISK_LEVELS,
  FIELD_INCIDENT_LOCATION_SOURCES,
} from '../config/field-incident.constants.js';

const pointSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      required: true,
      enum: ['Point'],
    },

    coordinates: {
      type: [Number],
      required: true,
    },
  },
  {
    _id: false,
  },
);

const locationSchema = new mongoose.Schema(
  {
    source: {
      type: String,
      required: true,
      enum: FIELD_INCIDENT_LOCATION_SOURCES,
    },

    point: {
      type: pointSchema,
      required: false,
    },

    description: {
      type: String,
      trim: true,
      maxlength: 500,
    },
  },
  {
    _id: false,
  },
);

const evidenceSchema = new mongoose.Schema(
  {
    publicId: {
      type: String,
      required: true,
      trim: true,
    },

    secureUrl: {
      type: String,
      required: true,
      trim: true,
    },

    resourceType: {
      type: String,
      required: true,
      enum: [
        'image',
        'video',
      ],
    },

    originalName: {
      type: String,
      required: true,
      trim: true,
    },

    mimeType: {
      type: String,
      required: true,
    },

    bytes: {
      type: Number,
      required: true,
      min: 1,
    },

    format: {
      type: String,
    },

    width: {
      type: Number,
    },

    height: {
      type: Number,
    },

    duration: {
      type: Number,
    },
  },
  {
    _id: false,
  },
);

const fieldIncidentSchema =
  new mongoose.Schema(
    {
      referenceNumber: {
        type: String,
        required: true,
        unique: true,
        index: true,
      },

      /*
       * Generated by the frontend.
       *
       * Used for idempotent retry when an
       * offline/pending incident is synchronized.
       */
      clientIncidentId: {
        type: String,
        trim: true,
        maxlength: 100,
      },

      rangerUserId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'User',
        index: true,
      },

      /*
       * Snapshots preserve the Ranger details
       * that existed when the incident was created.
       */
      rangerIdSnapshot: {
        type: String,
        required: true,
        trim: true,
      },

      assignedParkSnapshot: {
        type: String,
        required: true,
        trim: true,
      },

      incidentType: {
        type: String,
        required: true,
        enum: FIELD_INCIDENT_TYPES,
      },

      incidentDateTime: {
        type: Date,
        required: true,
      },

      riskLevel: {
        type: String,
        required: true,
        enum: FIELD_INCIDENT_RISK_LEVELS,
      },

      parkZone: {
        type: String,
        required: true,
        trim: true,
        maxlength: 150,
      },

      blockArea: {
        type: String,
        required: true,
        trim: true,
        maxlength: 150,
      },

      location: {
        type: locationSchema,
        required: true,
      },

      description: {
        type: String,
        required: true,
        trim: true,
        minlength: 10,
        maxlength: 1000,
      },

      additionalNotes: {
        type: String,
        trim: true,
        maxlength: 1000,
        default: '',
      },

      evidence: {
        type: [evidenceSchema],
        default: [],
      },

      status: {
        type: String,
        enum: [
          'SUBMITTED',
        ],
        default: 'SUBMITTED',
      },
    },
    {
      timestamps: true,
    },
  );

/*
 * Allows geospatial queries later.
 */
fieldIncidentSchema.index({
  'location.point': '2dsphere',
});

/*
 * Prevents the same Ranger's offline incident
 * from being saved more than once.
 *
 * Only documents that actually contain a
 * clientIncidentId are included in this index.
 */
fieldIncidentSchema.index(
  {
    rangerUserId: 1,
    clientIncidentId: 1,
  },
  {
    unique: true,

    partialFilterExpression: {
      clientIncidentId: {
        $type: 'string',
      },
    },
  },
);

export const FieldIncident =
  mongoose.models.FieldIncident
  || mongoose.model(
    'FieldIncident',
    fieldIncidentSchema,
  );